---
version: '3.7'
services:
    mysql:
        image: mysql:8.0.28
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'wichacks'
            MYSQL_USER: 'sir_hacksalot'
            MYSQL_PASSWORD: 'hallie-i-promise-i-know-a-couple-security-things'
            MYSQL_ROOT_PASSWORD: 'but-today-is-not-the-day-for-good-security'
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./mysqlStartupScripts/createMigrationTable.sql:/docker-entrypoint-initdb.d/0_init.sql
    api:
        image: wichacks-api:latest
        restart: always
        ports:
            - "5001:5000"
        environment:
            AUTH0_DOMAIN: 'wichacks.us.auth0.com'
            DBNAME: 'wichacks'
            AUTH0_CLIENT_ID: 'oTpWdnroYxfqQrprklhfXTGxIK5Vn8Df'
            AWS_DEFAULT_REGION: 'us-east-1'
            ENV: 'DEV'
        volumes:
            -   ~/.aws:/root/.aws:ro
    ui:
       image: wichacks-ui:latest
       restart: always
       ports:
            - "80:3000"
# Comment out Load Balancer for now
#    load-balancer:
#        build: ./loadBalancer
#        ports:
#            - "80:80"
#        restart: always

