---
version: '3.7'
services:
    api:
        image: ghcr.io/women-in-computing-at-rit/wichacker-manager/api:latest
        logging:
            options:
                awslogs-stream: api
        restart: always
        ports:
            - "5001:5000"
        environment:
            AUTH0_DOMAIN: 'wichacks.us.auth0.com'
            DBNAME: 'wichacks'
            AUTH0_CLIENT_ID: 'oTpWdnroYxfqQrprklhfXTGxIK5Vn8Df'
            AWS_DEFAULT_REGION: 'us-east-1'
            ENV: 'PROD'
        volumes:
            -   ~/.aws:/root/.aws:ro
    ui:
       image: ghcr.io/women-in-computing-at-rit/wichacker-manager/ui:latest
       restart: always
       ports:
            - "5002:3000"

