DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Permissions;
DROP TABLE IF EXISTS UserPermissions;
DROP TABLE IF EXISTS Sponsors;
DROP TABLE IF EXISTS Perks;
DROP TABLE IF EXISTS SponsorPerks;
DROP TABLE IF EXISTS Addresses;
DROP TABLE IF EXISTS Applications;
